export const mockAfiliados = [
    {
      id: 1,
      nombre: 'DATOS MOCK',
      ci: '1234567 LP',
      rubro: 'Industria',
      patentes: ['ABC-123', 'XYZ-789'],
      estado: 'Activo',
      telefono: '76543210',
      email: 'juan@example.com',
      direccion: 'Av. Principal #123, Zona Central',
      fechaRegistro: '2023-01-15',
      puestos: [
        {
          id: 1,
          nro: 101,
          fila: 'A',
          cuadra: '1',
          fecha_obtencion: '2023-01-20',
          rubro: 'Industria',
          estado: 'Activo',
        },
        {
          id: 2,
          nro: 205,
          fila: 'B',
          cuadra: '2',
          fecha_obtencion: '2023-03-10',
          rubro: 'Comercio',
          estado: 'Activo',
        },
      ]
    },
    {
      id: 2,
      nombre: 'María García Rodríguez',
      ci: '7654321 LP',
      rubro: 'Servicios',
      patentes: ['DEF-456'],
      estado: 'Activo',
      telefono: '71234567',
      email: 'maria@example.com',
      direccion: 'Calle Secundaria #456, Zona Norte',
      fechaRegistro: '2023-02-10',
      puestos: [
        {
          id: 3,
          nro: 312,
          fila: 'C',
          cuadra: '3',
          fecha_obtencion: '2023-02-15',
          rubro: 'Servicios',
          estado: 'Activo',
        },
      ]
    },
    {
      id: 3,
      nombre: 'Carlos López',
      ci: '9876543 LP',
      rubro: 'Comercio',
      patentes: ['GHI-789', 'JKL-012', 'MNO-345'],
      estado: 'Inactivo',
      telefono: '70123456',
      email: 'carlos@example.com',
      direccion: 'Av. Comercial #789',
      fechaRegistro: '2023-03-05',
      puestos: [
        {
          id: 4,
          nro: 418,
          fila: 'D',
          cuadra: '4',
          fecha_obtencion: '2023-03-12',
          rubro: 'Comercio',
          estado: 'Inactivo',
        },
        {
          id: 5,
          nro: 519,
          fila: 'E',
          cuadra: '5',
          fecha_obtencion: '2023-04-20',
          rubro: 'Servicios',
          estado: 'Inactivo',
        },
      ]
    },
    {
      id: 4,
      nombre: 'Ana Martínez',
      ci: '4567890 LP',
      rubro: 'Industria',
      patentes: ['PQR-678'],
      estado: 'Activo',
      telefono: '79876543',
      email: 'ana@example.com',
      direccion: 'Calle Industrial #321',
      fechaRegistro: '2023-04-15',
      puestos: [
        {
          id: 6,
          nro: 627,
          fila: 'F',
          cuadra: '6',
          fecha_obtencion: '2023-04-25',
          rubro: 'Industria',
          estado: 'Activo',
        },
      ]
    },
  ];